version: "3"
services:
  zhabogram:
    image: "zhabogram"
    container_name: "zhabogram"
## Modify ENV parameters to fit to your settings: TODO: make functional
#    environment:
#      - TELEGRAM_API_ID=17349
#      - TELEGRAM_API_HASH=344583e45741c457fe1862106095a5eb
#      - ZHABOGRAM_UPLOAD_URL=http://tlgrm.localhost #if reverse-proxy is set up to get SSL certificates use https://
#      - XMPP_UPLOAD_URL=http:///xmppfiles.localhost #if reverse-proxy is set up to get SSL certificates use https://
#      - XMPP_JID=tlgrm.localhost
#      - XMPP_HOST=127.0.0.1
#      - XMPP_PORT=8899
#      - XMPP_PASS=password
## Modify lables for Traefik.io reverse proxy
    labels:
      - traefik.backend=zhabogram
      - traefik.frontend.rule=Host:tlgrm.localhost
      - traefik.docker.network=web
      - traefik.port=80
      - traefik.enable=true
## Maps port 80 (localhost) to port 80 on the container. Use only for testing?     
#    ports:
#      - "80:80"
## Set a volume some that settings are not lost after shutting down the container. TODO: Needs fix
#    volumes:
#      - ./zhabogram-uploads:/var/www/zhabogram:rw
#      - ./zhabogram-db:/?/?/sessions.dat
# use existing network
networks:
  default:
    external:
      name: web
